spring.application.name=Client-Service
spring.datasource.url=jdbc:postgresql://localhost:5432/Clients_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082

# ===== KAFKA CONSUMER =====
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=client-service
spring.kafka.consumer.auto-offset-reset=earliest
