spring.application.name=Offer-Service

spring.datasource.url=jdbc:postgresql://localhost:5432/Offers_db
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8083

# ===== KAFKA =====
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=offer-service
spring.kafka.consumer.auto-offset-reset=earliest